# Local configuration
# the websites, admin and default
sites:
  "admin":
    webPath: "/admin"
    fsPath: "/sites/admin"
    controller: "\\Shaack\\Reboot\\AdminSite"
  "default":
    webPath: ""
    fsPath: "/sites/default"
    controller: "\\Shaack\\Reboot\\Site"

# 0 = debug, 1 = info, 2 = error
logLevel: 0