# AdminSite global values, like the navigation structure

navbar:
  brand: Reboot CMS
  structure: # No navigation in the admin interface for now
    Edit Pages: /pages
    Site Configuration: /config